### PR TITLE
version bumped for Traefik and compose

### PR DESCRIPTION
**Pull request by vegasbrianc**
Bumped Traefik to a supported version 1.3.5 and compose to version "3"

### CODE REVIEW

**Comment by nknapp** [comment]
Hi and thanks. I just noticed that I'm hardly working on this repo anymore. If you would like to help in handling things like this in the future, I would offer to add you to the team.

**Comment by vegasbrianc** [comment]
Hi @nknapp Sure, let me know how I can help.

**Comment by nknapp** [comment]
I have no specific plans for this repo for the future, but it would be good to keep things up to date (like you did in this PR) and maybe answer issues that come up.

**Comment by vegasbrianc** [comment]
Sounds like a plan

**Pull request merged**
